### ISSUE TITLE
More educative detail page

### ISSUE THREAD

**Issue by LilithWittmann** [zerforschung/schnelltesttest.de#4]
Currently, on the test detail page, we only show a list of parameters. However, I have the hypothesis, that these parameters are not self-explanatory.
**Hypothesis**: As a user, I want to learn more about the data related to my test. 

**TODO:**
- [ ] research the parameters
- [ ] write short educational texts about them
- [ ] design visualizations for the parameters related to data of all the other tests (to answer the question "Is this a good test compared to all the others")
- [ ] implement it

**Comment by ewatch** [comment]
@LilithWittmann 
I can only agree on the topic to show the details of the test related to other test details because in the end if one wants to know if another test is better then the test one is using.

**Comment by LilithWittmann** [comment]
Last design:
<img width="503" alt="Screenshot 2022-01-23 at 22 41 01" src="https://user-images.githubusercontent.com/891030/150698994-eaf568f0-366a-4dc3-8b5e-b090b225702d.png">

**Comment by bunchofsage** [comment]
I think the chart visualization is not necessary (and not that intuitive: why is it two dimensional? It looks like it makes a difference whether I look above the horizontal line or below).

However, when I see the "better than 90 other tests" paragraph I instantly want to see: oh wow, point me to the sensitivity-descending sorted list where I see my test in between! Maybe that's more interesting?

Concerning:
> design visualizations for the parameters
What about joining forces with the data viz team behind http://swr.li/schnelltests or https://twitter.com/funkeinteraktiv/status/1483828806934798336 (morgenpost.de). Or ask @PEI_Germany to clarify what "Sehr hoch, hoch, niedrig" categories really mean. I read misleading tweets.
